### ISSUE TITLE
[WIP] cannot remove afterimage made by #sprite

### ISSUE THREAD

**Issue by remore** [remore/burn#20]
As this series of tweets explains, there should be an certain option to remove afterimage made by `#sprite`. 
https://twitter.com/remore/status/771652872400310273

**Comment by mofukuma** [comment]
原因はシーンのメインループ先頭でObject Attribute Memoryをクリアしていないためと思われます。

とりあえずメインループ先頭にinline "oam_clear();"を入れると直りました。

shootingデモの例
![image](https://cloud.githubusercontent.com/assets/3530659/18335328/8f85b014-75b9-11e6-8685-a1494f7a218a.png)

**Comment by remore** [comment]
確認しました〜こっちの方がキビキビ動作してゲームが楽しくなりますね🎮

いずれFuel DSLにもこのHackを反映させようと思うのですが、ひとまずFUEL-ROM.mdに解説という形で解説を加えました。フィードバックありがとうございます！ @mofukuma 
https://github.com/remore/burn/commit/1be92c730afb7bcd5c65299c69f725b02e91b731
